### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by seryl** [blakesmith/go-grok#1]
Hey Blake, do you plan on providing an MIT or apache-equivalent license for this?

I'm sure people would love to use this. Grok itself is fantastically useful.

**Comment by blakesmith** [comment]
Absolutely! I totally forgot to include a license. If you send me a PR with the MIT license included, I'd be happy to merge it!

Are you doing anything cool with Grok?

Cheers,

Blake

**Comment by seryl** [comment]
Yea, absolutely, I wanted to use it for a software router we're using at Ooyala.

It exports logs in the same fashion that haproxy does and we wanted to make a tool that provides a drilldown for backend services. Hopefully by the end of the weekend we tie in some profiling // sampling tools for ruby and golang.

Basically we want to make the below very straightforward:

app -> region -> container -> profiling data
region -> app -> container -> profiling data

Looking at integrating graphviz graphs and brendan gregg's flamegraphs.
