### ISSUE TITLE
Goal? Fully compliant with grok?

### ISSUE THREAD

**Issue by ChristianKniep** [blakesmith/go-grok#3]
Hey Blake,

is the goal of this project to be fully compliant with grok and free myself (maybe not only me, let's be honest) from getting my hands dirty with ruby?

Cheers from Paris
Christian

**Comment by blakesmith** [comment]
Hey Christian,

The project was started as a way to integrate grok into an existing Go project. Since grok is a C library, I wanted to be able to call into it from my go runtime. I'm not really sure where ruby fits in?

What are you wanting to use grok for?

Blake

**Comment by ChristianKniep** [comment]
Salut Blake,

I am using logstash to fetch logs and created a little script to check my grok patterns.
But this needs ruby and it is kind of painful to maintain (need ruby 1.9.2 while newer OS come with 2.0.0; such pain points).

Furthermore I don't want to dig into ruby, because my toolbox already includes python. GO on the other hand is something I want to add to my toolbox anyway. So using grok within go to play around would be cool.

Cheers
Christian

**Comment by ChristianKniep** [comment]
When I find some time (TM) to play around with golang and grok, I will revisit go-grok.

Thx, looks interesting.. :)
